name: ninja_openssl
description: Dart library to encrypt and sign using openssl.
version: 1.0.4
homepage: https://github.com/ninja-dart/openssl
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.3.1 <3.0.0'

dependencies:
  path: ^1.8.1
  ninja_hex: ^2.0.1

dev_dependencies:
#  unittest: any
